# Generated by Django 4.2.13 on 2026-05-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApprovalRequest",
        ),
    ]
