# Generated by Django 4.2.13 on 2026-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facedescriptor",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
