# Generated by Django 4.2.13 on 2026-05-03 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectallocation",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="tenants.college",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="academic.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="tenants.college",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="academic.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="class_coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinating_divisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="tenants.college",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="tenants.college",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="hod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_department",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tenants.college",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="tenants.college",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectallocation",
            unique_together={("subject", "teacher", "division", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("college", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together={("course", "academic_year", "name", "year_of_study")},
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("college", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("college", "code")},
        ),
    ]
