# Generated by Django 4.2.13 on 2026-05-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_college_logo_url"),
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("college", "name")},
        ),
    ]
