# Generated by Django 4.2.13 on 2026-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceregistry",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deviceregistry",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deviceregistry",
            name="normalized_device_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
