# Generated by Django 4.2.13 on 2026-05-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendancesession",
            old_name="lat",
            new_name="teacher_lat",
        ),
        migrations.RenameField(
            model_name="attendancesession",
            old_name="lng",
            new_name="teacher_lng",
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="compass_direction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="device_movement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="teacher_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="teacher_altitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
