# Generated by Django 4.2.13 on 2026-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_rename_lat_attendancesession_teacher_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="gps_accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="is_mocked_gps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="security_flags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
