# Generated by Django 4.2.13 on 2026-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendancelog_gps_accuracy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
