# Generated by Django 4.2.13 on 2026-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="logo_url",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
