# Generated by Django 4.2.13

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('floor_number', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=60)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_rooms', to='tenants.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomCorner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corner_index', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corners', to='virtual_rooms.virtualroom')),
            ],
            options={
                'db_table': 'room_corner',
                'ordering': ['room', 'corner_index'],
                'unique_together': {('room', 'corner_index')},
            },
        ),
    ]
