# Generated by Django 4.2.13 on 2026-05-03 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("floor_number", models.IntegerField(default=0)),
                ("center_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("center_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("radius_meters", models.FloatField(default=30.0)),
                ("min_altitude", models.FloatField(default=0.0)),
                ("max_altitude", models.FloatField(default=50.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_rooms",
                        to="tenants.college",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_virtual_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "virtual_rooms_virtualroom",
            },
        ),
    ]
