# Generated by Django 4.2.13 on 2026-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcorner",
            name="accuracy_meters",
            field=models.FloatField(default=0.0),
        ),
    ]
