# Generated by Django 4.2.13 on 2026-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualroom",
            name="capacity",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="corner_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of 4 corner GPS coordinates [{lat, lng, alt, accuracy}, ...]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="estimated_area",
            field=models.FloatField(blank=True, help_text="Square meters", null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="estimated_length",
            field=models.FloatField(blank=True, help_text="Meters", null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="estimated_width",
            field=models.FloatField(blank=True, help_text="Meters", null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="room_orientation",
            field=models.FloatField(
                blank=True, help_text="Compass heading degrees", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="use_polygon",
            field=models.BooleanField(
                default=False,
                help_text="If True, uses polygon boundary. If False, uses radius-based.",
            ),
        ),
    ]
