# Generated by Django 4.2.13 on 2026-05-14 15:42

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_rooms", "0002_add_polygon_3d_boundary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="virtualroom",
            options={"ordering": ["building", "floor_number", "name"]},
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="corner_coordinates",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="estimated_area",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="estimated_length",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="estimated_width",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="room_orientation",
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="altitude_tolerance",
            field=models.FloatField(
                default=3.0, help_text="±Meters added to captured min/max altitude"
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="area",
            field=models.FloatField(
                blank=True, help_text="Polygon area (m²)", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="boundary_polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="length",
            field=models.FloatField(
                blank=True, help_text="C1→C2 distance (meters)", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="magnetic_heading",
            field=models.FloatField(
                blank=True, help_text="Primary room axis degrees (C1→C2)", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="width",
            field=models.FloatField(
                blank=True, help_text="C1→C4 distance (meters)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="virtualroom",
            name="center_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virtualroom",
            name="center_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virtualroom",
            name="use_polygon",
            field=models.BooleanField(
                default=False,
                help_text="True when 4 corners captured and spatial vectors computed",
            ),
        ),
        migrations.CreateModel(
            name="SpatialVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_point", models.JSONField(help_text="{lat, lng, alt}")),
                ("x_axis_vector", models.JSONField(help_text="{x, y, z, mag}  C1→C2")),
                ("y_axis_vector", models.JSONField(help_text="{x, y, z, mag}  C1→C4")),
                (
                    "z_axis_vector",
                    models.JSONField(
                        help_text="{x, y, z}       cross product (vertical)"
                    ),
                ),
                (
                    "x_extent",
                    models.FloatField(help_text="Room length along X-axis (meters)"),
                ),
                (
                    "y_extent",
                    models.FloatField(help_text="Room width along Y-axis (meters)"),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_vectors",
                        to="virtual_rooms.virtualroom",
                    ),
                ),
            ],
            options={
                "db_table": "virtual_rooms_spatialvector",
            },
        ),
        migrations.CreateModel(
            name="AttendanceLocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_lat", models.FloatField()),
                ("submitted_lng", models.FloatField()),
                ("submitted_alt", models.FloatField()),
                ("gps_accuracy", models.FloatField(blank=True, null=True)),
                ("is_valid", models.BooleanField()),
                ("validation_mode", models.CharField(max_length=20)),
                ("inside_2d", models.BooleanField(null=True)),
                ("altitude_ok", models.BooleanField(null=True)),
                ("local_x", models.FloatField(null=True)),
                ("local_y", models.FloatField(null=True)),
                ("local_z", models.FloatField(null=True)),
                ("confidence", models.FloatField(null=True)),
                ("sensor_snapshot", models.JSONField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="virtual_rooms.virtualroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "virtual_rooms_attendancelocationlog",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomCorner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "corner_index",
                    models.IntegerField(
                        help_text="1=origin, 2=X-axis, 3=opposite, 4=Y-axis"
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("altitude", models.FloatField()),
                (
                    "accuracy",
                    models.FloatField(help_text="GPS horizontal accuracy (meters)"),
                ),
                (
                    "altitude_accuracy",
                    models.FloatField(
                        default=5.0, help_text="GPS vertical accuracy (meters)"
                    ),
                ),
                ("heading", models.FloatField(help_text="Compass heading (0–360°)")),
                ("pitch", models.FloatField(help_text="Device pitch (degrees)")),
                ("roll", models.FloatField(help_text="Device roll (degrees)")),
                (
                    "yaw",
                    models.FloatField(
                        help_text="Device yaw (degrees, same as heading in NED frame)"
                    ),
                ),
                ("accelerometer_data", models.JSONField(blank=True, null=True)),
                ("gyroscope_data", models.JSONField(blank=True, null=True)),
                ("magnetic_field_data", models.JSONField(blank=True, null=True)),
                (
                    "barometric_pressure",
                    models.FloatField(blank=True, help_text="hPa", null=True),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corners",
                        to="virtual_rooms.virtualroom",
                    ),
                ),
            ],
            options={
                "db_table": "virtual_rooms_roomcorner",
                "ordering": ["corner_index"],
                "unique_together": {("room", "corner_index")},
            },
        ),
    ]
