# Generated by Django 4.2.13 on 2026-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0002_roomcorner_accuracy_meters"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcorner",
            name="sensor_telemetry",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="area_sq_meters",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="orientation_degrees",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="perimeter_meters",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="reconstruction_quality",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="spatial_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
