# Generated by Django 4.2.13 on 2026-05-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0003_alter_virtualroom_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpatialMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "virtual_rooms_spatialmetadata",
            },
        ),
        migrations.AlterModelOptions(
            name="virtualroom",
            options={"ordering": ["building", "floor", "room_name"]},
        ),
        migrations.RenameField(
            model_name="roomcorner",
            old_name="accelerometer_data",
            new_name="accelerometer",
        ),
        migrations.RenameField(
            model_name="roomcorner",
            old_name="gyroscope_data",
            new_name="gyroscope",
        ),
        migrations.RenameField(
            model_name="roomcorner",
            old_name="magnetic_field_data",
            new_name="magnetic_field",
        ),
        migrations.RenameField(
            model_name="roomcorner",
            old_name="captured_at",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="virtualroom",
            old_name="floor_number",
            new_name="floor",
        ),
        migrations.RenameField(
            model_name="virtualroom",
            old_name="boundary_polygon",
            new_name="polygon",
        ),
        migrations.RenameField(
            model_name="virtualroom",
            old_name="name",
            new_name="room_name",
        ),
        migrations.RemoveField(
            model_name="attendancelocationlog",
            name="altitude_ok",
        ),
        migrations.RemoveField(
            model_name="attendancelocationlog",
            name="inside_2d",
        ),
        migrations.RemoveField(
            model_name="roomcorner",
            name="altitude_accuracy",
        ),
        migrations.RemoveField(
            model_name="roomcorner",
            name="barometric_pressure",
        ),
        migrations.RemoveField(
            model_name="roomcorner",
            name="location",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="altitude_tolerance",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="area",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="length",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="magnetic_heading",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="radius_meters",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="use_polygon",
        ),
        migrations.RemoveField(
            model_name="virtualroom",
            name="width",
        ),
        migrations.AddField(
            model_name="attendancelocationlog",
            name="spoof_flags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="roomcorner",
            name="latitude",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomcorner",
            name="longitude",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="normalized_coordinates",
            field=models.JSONField(
                blank=True, help_text="Corners in local metres", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="orientation_matrix",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="polygon_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="room_dimensions",
            field=models.JSONField(
                blank=True, help_text="{length, width, height}", null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="x_axis_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="y_axis_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="z_axis_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomcorner",
            name="accuracy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="roomcorner",
            name="corner_index",
            field=models.IntegerField(help_text="1 to 4"),
        ),
        migrations.AlterField(
            model_name="roomcorner",
            name="pitch",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="roomcorner",
            name="roll",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="roomcorner",
            name="yaw",
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name="SpatialVector",
        ),
        migrations.AddField(
            model_name="spatialmetadata",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spatial_metadata",
                to="virtual_rooms.virtualroom",
            ),
        ),
    ]
