# Generated by Django 4.2.13 on 2026-05-28 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0002_alter_college_logo_url"),
        ("virtual_rooms", "0003_roomcorner_sensor_telemetry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomPresence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("last_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("last_accuracy", models.FloatField(default=10.0)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("is_inside", models.BooleanField(default=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_presence",
                        to="tenants.college",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_records",
                        to="virtual_rooms.virtualroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_presence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "room_presence",
                "indexes": [
                    models.Index(
                        fields=["room", "is_inside"],
                        name="room_presen_room_id_ebdac2_idx",
                    ),
                    models.Index(
                        fields=["user", "is_inside"],
                        name="room_presen_user_id_e86fa9_idx",
                    ),
                ],
                "unique_together": {("room", "user", "entered_at")},
            },
        ),
        migrations.CreateModel(
            name="RoomEntryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("exit", "Exit"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("accuracy", models.FloatField(default=10.0)),
                ("is_polygon_validated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_entry_logs",
                        to="tenants.college",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_logs",
                        to="virtual_rooms.virtualroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_entry_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "room_entry_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["room", "event", "timestamp"],
                        name="room_entry__room_id_0d30a7_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="room_entry__user_id_dc2669_idx",
                    ),
                ],
            },
        ),
    ]
