# Generated by Django 4.2.13 on 2026-05-31 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_rooms", "0004_roompresence_roomentrylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualRoomAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("validated", "Validated"),
                            ("certified", "Certified"),
                            ("activated", "Activated"),
                            ("deactivated", "Deactivated"),
                            ("duplicate_blocked", "Duplicate Blocked"),
                            ("security_flagged", "Security Flagged"),
                            ("edit", "Edited"),
                        ],
                        max_length=30,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=50)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("gps_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "virtual_room_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualRoomSecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("mock_location", "Mock Location Detected"),
                            ("fake_gps", "Fake GPS App Detected"),
                            ("coordinate_jump", "Impossible Coordinate Jump"),
                            ("rapid_oscillation", "Rapid Coordinate Oscillation"),
                            ("suspicious_coordinates", "Suspicious Coordinates"),
                            ("invalid_geometry", "Invalid Geometry"),
                            ("spoofing_suspected", "Spoofing Suspected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("flag_detail", models.JSONField(blank=True, default=dict)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "virtual_room_security_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="boundary_geojson",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="gps_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="gps_health_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="length_meters",
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="location_method",
            field=models.CharField(
                choices=[("gps", "GPS Capture"), ("manual", "Manual Coordinates")],
                default="gps",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="room_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("created", "Created"),
                    ("validated", "Validated"),
                    ("certified", "Certified"),
                    ("active", "Active"),
                    ("deactivated", "Deactivated"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="virtualroom",
            name="width_meters",
            field=models.FloatField(default=10.0),
        ),
        migrations.AddIndex(
            model_name="virtualroom",
            index=models.Index(
                fields=["college", "department"], name="virtual_roo_college_b06baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroom",
            index=models.Index(
                fields=["college", "status"], name="virtual_roo_college_2686d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroom",
            index=models.Index(
                fields=["is_deleted"], name="virtual_roo_is_dele_a5dfa6_idx"
            ),
        ),
        migrations.AddField(
            model_name="virtualroomsecuritylog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_security_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualroomsecuritylog",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_logs",
                to="virtual_rooms.virtualroom",
            ),
        ),
        migrations.AddField(
            model_name="virtualroomauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualroomauditlog",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="virtual_rooms.virtualroom",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroomsecuritylog",
            index=models.Index(
                fields=["room", "flag_type"], name="virtual_roo_room_id_9efef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroomsecuritylog",
            index=models.Index(
                fields=["actor", "created_at"], name="virtual_roo_actor_i_3f394f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroomauditlog",
            index=models.Index(
                fields=["room", "event_type"], name="virtual_roo_room_id_23203d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroomauditlog",
            index=models.Index(
                fields=["actor", "created_at"], name="virtual_roo_actor_i_d2708d_idx"
            ),
        ),
    ]
