# Generated by Django 4.2.13 on 2026-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0004_spatialmetadata_alter_virtualroom_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomcorner",
            name="heading",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="virtualroom",
            name="normalized_coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virtualroom",
            name="room_dimensions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="virtualroom",
            index=models.Index(
                fields=["college", "is_active"], name="virtual_roo_college_55abca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualroom",
            index=models.Index(
                fields=["building", "floor"], name="virtual_roo_buildin_a70e76_idx"
            ),
        ),
    ]
