# Generated by Django 4.2.13 on 2026-05-17 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_rooms", "0005_alter_roomcorner_heading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("device_model", models.CharField(blank=True, max_length=128)),
                ("os_version", models.CharField(blank=True, max_length=64)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("avg_gps_accuracy", models.FloatField(blank=True, null=True)),
                ("corners_captured", models.IntegerField(default=0)),
                (
                    "capture_method",
                    models.CharField(
                        choices=[
                            ("gps", "GPS-Based"),
                            ("ar_slam", "AR SLAM"),
                            ("manual", "Manual Input"),
                        ],
                        default="gps",
                        max_length=20,
                    ),
                ),
                (
                    "local_geometry",
                    models.JSONField(
                        blank=True,
                        help_text="XYZ corners relative to origin",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_sessions",
                        to="virtual_rooms.virtualroom",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "virtual_rooms_scansession",
                "ordering": ["-started_at"],
            },
        ),
    ]
