# Generated by Django 4.2.13 on 2026-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_rooms", "0005_virtualroomauditlog_virtualroomsecuritylog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualroom",
            name="location_method",
            field=models.CharField(
                choices=[
                    ("gps", "GPS Capture"),
                    ("manual", "Manual Coordinates"),
                    ("map_click", "Map Click"),
                    ("walk_corner", "Walk Corner"),
                    ("coord_area", "Coordinate + Area"),
                ],
                default="gps",
                max_length=20,
            ),
        ),
    ]
